# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='auth.proto',
  package='tnp',
  serialized_pb='\n\nauth.proto\x12\x03tnp\";\n\x15\x41uthenticationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\x0c\"\xc2\x01\n\x16\x41uthenticationResponse\x12\x32\n\x06status\x18\x01 \x01(\x0e\x32\".tnp.AuthenticationResponse.Status\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nauth_token\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x04 \x01(\r\">\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x0c\n\x08\x42\x41\x44_USER\x10\x01\x12\x0c\n\x08\x42\x41\x44_PASS\x10\x02\x12\x10\n\x0cSERVER_ERROR\x10\x03')



_AUTHENTICATIONRESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='tnp.AuthenticationResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD_USER', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BAD_PASS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SERVER_ERROR', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=213,
  serialized_end=275,
)


_AUTHENTICATIONREQUEST = _descriptor.Descriptor(
  name='AuthenticationRequest',
  full_name='tnp.AuthenticationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='tnp.AuthenticationRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='tnp.AuthenticationRequest.password', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=19,
  serialized_end=78,
)


_AUTHENTICATIONRESPONSE = _descriptor.Descriptor(
  name='AuthenticationResponse',
  full_name='tnp.AuthenticationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='tnp.AuthenticationResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='tnp.AuthenticationResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auth_token', full_name='tnp.AuthenticationResponse.auth_token', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='tnp.AuthenticationResponse.user_id', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _AUTHENTICATIONRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=81,
  serialized_end=275,
)

_AUTHENTICATIONRESPONSE.fields_by_name['status'].enum_type = _AUTHENTICATIONRESPONSE_STATUS
_AUTHENTICATIONRESPONSE_STATUS.containing_type = _AUTHENTICATIONRESPONSE;
DESCRIPTOR.message_types_by_name['AuthenticationRequest'] = _AUTHENTICATIONREQUEST
DESCRIPTOR.message_types_by_name['AuthenticationResponse'] = _AUTHENTICATIONRESPONSE

class AuthenticationRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHENTICATIONREQUEST

  # @@protoc_insertion_point(class_scope:tnp.AuthenticationRequest)

class AuthenticationResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUTHENTICATIONRESPONSE

  # @@protoc_insertion_point(class_scope:tnp.AuthenticationResponse)


# @@protoc_insertion_point(module_scope)
